export const demoMovies = [
  { id: 550, title: 'Fight Club', poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', backdrop_path: '/hZkgoQYus5vegHoetLkCJzb17zJ.jpg', release_date: '1999-10-15', vote_average: 8.4, overview: 'An office worker and a charismatic soap maker form an underground fight club that evolves into something much bigger.', genres: [{ id: 18, name: 'Drama' }, { id: 53, name: 'Thriller' }] },
  { id: 27205, title: 'Inception', poster_path: '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg', backdrop_path: '/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg', release_date: '2010-07-16', vote_average: 8.4, overview: 'A skilled thief who steals corporate secrets through dream-sharing technology is given one final, impossible job.', genres: [{ id: 28, name: 'Action' }, { id: 878, name: 'Science Fiction' }] },
  { id: 155, title: 'The Dark Knight', poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', backdrop_path: '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg', release_date: '2008-07-16', vote_average: 8.5, overview: 'Batman faces a brilliant criminal mastermind who plunges Gotham City into chaos.', genres: [{ id: 18, name: 'Drama' }, { id: 28, name: 'Action' }] },
  { id: 238, title: 'The Godfather', poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg', release_date: '1972-03-14', vote_average: 8.7, overview: 'The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.', genres: [{ id: 18, name: 'Drama' }, { id: 80, name: 'Crime' }] },
  { id: 680, title: 'Pulp Fiction', poster_path: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg', release_date: '1994-09-10', vote_average: 8.5, overview: 'The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine in four unforgettable tales.', genres: [{ id: 53, name: 'Thriller' }, { id: 80, name: 'Crime' }] },
  { id: 496243, title: 'Parasite', poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', backdrop_path: '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg', release_date: '2019-05-30', vote_average: 8.5, overview: 'A struggling family slowly ingratiates themselves with a wealthy household with unexpected consequences.', genres: [{ id: 35, name: 'Comedy' }, { id: 53, name: 'Thriller' }] },
  { id: 13, title: 'Forrest Gump', poster_path: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', backdrop_path: '/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg', release_date: '1994-06-23', vote_average: 8.5, overview: 'A kind-hearted man with a low IQ experiences defining moments of the twentieth century.', genres: [{ id: 35, name: 'Comedy' }, { id: 18, name: 'Drama' }] },
  { id: 11, title: 'Star Wars', poster_path: '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg', backdrop_path: '/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg', release_date: '1977-05-25', vote_average: 8.2, overview: 'A farm boy joins a daring rescue mission and begins a journey to restore freedom to the galaxy.', genres: [{ id: 12, name: 'Adventure' }, { id: 878, name: 'Science Fiction' }] }
];

export const findDemoMovie = (id) => demoMovies.find((movie) => String(movie.id) === String(id));
